Mappings:
  AmiRegionMap:
    us-east-1:
      "AMI": "ami-0b5eea76982371e91"
    us-east-2:
      "AMI": "ami-0a606d8395a538502"
    us-west-1:
      "AMI": "ami-00d8a762cb0c50254"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, ins, from, cloudformation]]
      SecurityGroups:
        - !Ref  VprofileSG

  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MySecurityGroup
      GroupDescription: Allow ssh & http from anywhere
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0